width = float(input('ป้อนความกว้าง : '))
long = float(input('ป้อนความยาว : '))
high = float(input('ป้อนความสูง : '))
print('----------------------------')
total_area = round(((width * long * 2) + (width * high * 2) + (long * high *2))/5)
print(f"จะได้กล่อง กว้าง {width} ยาว {long} สูง {high} ต้องใช้สีทั้งหมด {total_area} แกลอน")
